# Generated by Django 3.1.6 on 2022-02-18 20:26

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0002_auto_20220218_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='company',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
