# Generated by Django 3.1.6 on 2022-02-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0004_auto_20220218_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymodel',
            name='shareholder',
        ),
    ]
