# Generated by Django 3.1.6 on 2022-02-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0007_exchangemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Programmer',
        ),
    ]
