# Generated by Django 3.1.6 on 2022-02-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0008_auto_20220227_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='res',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
