# Generated by Django 3.1.6 on 2022-02-27 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0009_companymodel_res'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymodel',
            name='res',
        ),
    ]
