# Generated by Django 3.1.6 on 2022-03-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0012_auto_20220308_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
