# Generated by Django 3.1.6 on 2021-03-26 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationCompanyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'PublicationCompanyModel',
            },
        ),
        migrations.CreateModel(
            name='PublicationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateField()),
                ('research_category', models.CharField(choices=[('Models', 'Models'), ('Newsletters', 'Newsletters'), ('Commentaries', 'Commentaries'), ('Reports', 'Reports')], max_length=100)),
                ('research_type', models.CharField(choices=[('', 'Type'), ('Valuation Models', 'Valuation Models'), ('Daily Market Briefing', 'Daily Market Briefing'), ('Weekly comments', 'Weekly comments'), ('Quarterly Results', 'Quarterly Results'), ('Half Year Results', 'Half Year Results'), ('Annual Results', 'Annual Results'), ('Annual Shareholder Meeting', 'Annual Shareholder Meeting'), ('IPO Analysis', 'IPO Analysis'), ('Research Notes', 'Research Notes'), ('Sector Reports', 'Sector Reports'), ('Strategic Reports', 'Strategic Reports'), ('Economic Notes', 'Economic Notes'), ('Investor Conference', 'Investor Conference')], max_length=100)),
                ('subject', models.CharField(max_length=150)),
                ('publication_desc', models.CharField(max_length=250)),
                ('file_name', models.FileField(upload_to='publications/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visible_flag', models.BooleanField(default=True)),
                ('edited_by', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jdapublicationsapp.publicationcompanymodel')),
            ],
            options={
                'verbose_name_plural': 'PublicationModel',
            },
        ),
    ]
