# Generated by Django 3.1.6 on 2021-05-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdapublicationsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubTempModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watermark_pdf', models.FileField(upload_to='publications/%Y/%m/')),
            ],
        ),
    ]
