# Generated by Django 3.1.6 on 2021-05-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdapublicationsapp', '0002_pubtempmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationmodel',
            name='tmp_file_name',
            field=models.FileField(blank=True, null=True, upload_to='publications/%Y/%m/'),
        ),
    ]
