# Generated by Django 3.1.6 on 2021-05-25 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdapublicationsapp', '0004_auto_20210525_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationmodel',
            name='tmp_pdf_file',
        ),
    ]
