# Generated by Django 3.1.6 on 2021-06-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdapublicationsapp', '0005_remove_publicationmodel_tmp_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationmodel',
            name='pub_language',
            field=models.CharField(choices=[('English', 'English'), ('French', 'French')], default='English', max_length=100),
        ),
    ]
