# Generated by Django 3.1.6 on 2021-06-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdapublicationsapp', '0007_auto_20210622_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationmodel',
            name='research_type',
            field=models.CharField(choices=[('', 'Type'), ('Daily Briefing', 'Daily Briefing'), ('Quarterly Results', 'Quarterly Results'), ('Half Year Results', 'Half Year Results'), ('Annual Results', 'Annual Results'), ('Stakeholder Meeting Feedback', 'Stakeholder Meeting Feedback'), ('IPO Analysis', 'IPO Analysis'), ('Research Notes', 'Research Notes'), ('Sector Reports', 'Sector Reports'), ('Strategic Reports', 'Strategic Reports'), ('Economic Notes', 'Economic Notes'), ('Investment Case', 'Investment Case')], max_length=100),
        ),
    ]
