# Generated by Django 3.1.6 on 2022-03-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdapublicationsapp', '0010_productmetamodel_productmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductMetaModel',
        ),
        migrations.DeleteModel(
            name='ProductModel',
        ),
    ]
