# Generated by Django 3.1.6 on 2021-05-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210521_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='logo',
            field=models.ImageField(default='/profile_logo/default.jpg', upload_to='profile_logo'),
        ),
    ]
