# Generated by Django 3.1.6 on 2021-05-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210521_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='logo',
            field=models.ImageField(default='default.jpg', upload_to='profile_logo'),
        ),
    ]
