# Generated by Django 3.1.6 on 2021-10-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_profile_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='logo',
            field=models.ImageField(default='profile_logo/default.jpg', upload_to='profile_logo'),
        ),
    ]
