# Generated by Django 3.1.6 on 2021-04-10 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='jdatesterCompanyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'jdatesterCompanyModel',
            },
        ),
        migrations.CreateModel(
            name='jdatesterLineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lbl', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'jdatesterLineModel',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('computed', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name_plural': 'TestModel',
            },
        ),
        migrations.CreateModel(
            name='jdatesterLinkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('brut_1', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('brut_2', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('amort_1', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('amort_2', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('net_1', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('net_2', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jdatester.jdatestercompanymodel')),
            ],
            options={
                'verbose_name_plural': 'jdatesterLinkModel',
            },
        ),
        migrations.CreateModel(
            name='jdatesterBalanceSheetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('brut', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('amort', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('net', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jdatester.jdatestercompanymodel')),
                ('lbl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jdatester.jdatesterlinemodel')),
            ],
            options={
                'verbose_name_plural': 'jdatesterBalanceSheetModel',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('student', models.ManyToManyField(to='jdatester.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jdatester.author')),
            ],
        ),
    ]
