# Generated by Django 3.1.6 on 2021-04-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdatester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('day_started', models.DateField()),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
