# Generated by Django 3.1.6 on 2021-04-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdatester', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadExcelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=60)),
                ('day_started', models.DateField()),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
