# Generated by Django 3.1.6 on 2021-04-25 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdatester', '0003_uploadexcelmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadexcelmodel',
            name='day_started',
        ),
    ]
