# Generated by Django 3.1.6 on 2021-04-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdatester', '0004_remove_uploadexcelmodel_day_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPriceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_date', models.DateTimeField()),
                ('index', models.CharField(max_length=10)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
            ],
        ),
    ]
