# Generated by Django 3.1.6 on 2021-04-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdatester', '0009_auto_20210426_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitypricemodel',
            name='avg_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
