# Generated by Django 3.1.6 on 2021-04-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdatester', '0011_auto_20210426_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitypricemodel',
            name='avg_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
