# Generated by Django 3.1.6 on 2021-04-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdatester', '0012_auto_20210427_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitypricemodel',
            name='open',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
