# Generated by Django 3.1.6 on 2021-05-02 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jdatester', '0016_auto_20210427_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexpricemodel',
            options={'verbose_name_plural': 'IndexPriceModel'},
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'teams',
                'permissions': [('can_edit_team', 'Can edit team')],
            },
        ),
    ]
