# Generated by Django 3.1.6 on 2022-02-20 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdatester', '0018_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndexPriceModel',
        ),
        migrations.RemoveField(
            model_name='securitypricemodel',
            name='security',
        ),
        migrations.DeleteModel(
            name='SecurityModel',
        ),
        migrations.DeleteModel(
            name='SecurityPriceModel',
        ),
    ]
