# Generated by Django 3.1.6 on 2021-05-02 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexpricemodel',
            options={'verbose_name_plural': 'IndexPriceModel'},
        ),
        migrations.AlterModelOptions(
            name='securitymodel',
            options={'verbose_name_plural': 'SecurityModel'},
        ),
        migrations.AlterModelOptions(
            name='securitypricemodel',
            options={'verbose_name_plural': 'SecurityPriceModel'},
        ),
    ]
