# Generated by Django 3.1.6 on 2022-02-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0005_securitymodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitymodel',
            name='res',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
