# Generated by Django 3.1.6 on 2022-02-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0006_securitymodel_res'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('acronym', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'ExchangeModel',
            },
        ),
        migrations.RemoveField(
            model_name='securitymodel',
            name='res',
        ),
    ]
