# Generated by Django 3.1.6 on 2022-02-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0008_exchangemodel_res'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangemodel',
            name='res',
        ),
    ]
