# Generated by Django 3.1.6 on 2022-02-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0009_remove_exchangemodel_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitymodel',
            name='close_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securitymodel',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='securitymodel',
            name='instr_type',
            field=models.CharField(blank=True, choices=[('', 'Security Status'), ('Listed', 'Listed'), ('Unquoted', 'Unquoted'), ('Suspended', 'Suspended')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='securitymodel',
            name='isu_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securitymodel',
            name='open_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
