# Generated by Django 3.1.6 on 2022-02-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0012_bondmodel_stockmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmodel',
            name='res',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
