# Generated by Django 3.1.6 on 2022-02-19 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0013_stockmodel_res'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmodel',
            name='res',
        ),
    ]
