# Generated by Django 3.1.6 on 2022-02-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0014_remove_stockmodel_res'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexmodel',
            old_name='index',
            new_name='idx',
        ),
        migrations.RenameField(
            model_name='indexpricemodel',
            old_name='index',
            new_name='idx',
        ),
    ]
