# Generated by Django 3.1.6 on 2022-02-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0015_auto_20220220_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpricemodel',
            name='res',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
