# Generated by Django 3.1.6 on 2022-02-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0019_auto_20220227_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitymodel',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
