# Generated by Django 3.1.6 on 2022-02-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0020_securitymodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondmodel',
            name='gr_bnd_int_rate',
        ),
        migrations.RemoveField(
            model_name='bondmodel',
            name='net_bnd_int_rate',
        ),
        migrations.AddField(
            model_name='bondmodel',
            name='nbr_shrs_outstg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
