# Generated by Django 3.1.6 on 2022-02-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0021_auto_20220228_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondmodel',
            name='gr_bnd_int_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bondmodel',
            name='net_bnd_int_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
