# Generated by Django 3.1.6 on 2022-02-28 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0022_auto_20220228_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitymodel',
            name='instr_type',
        ),
    ]
