# Generated by Django 3.1.6 on 2022-02-28 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0023_remove_securitymodel_instr_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bondmodel',
            old_name='bnd_isu_dt',
            new_name='first_pay_dt',
        ),
        migrations.RenameField(
            model_name='bondmodel',
            old_name='first_pay_date',
            new_name='isu_dt',
        ),
        migrations.RemoveField(
            model_name='bondmodel',
            name='security_date',
        ),
    ]
