# Generated by Django 3.1.6 on 2022-02-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0024_auto_20220228_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondmodel',
            name='dfrrd_rpymt_perd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bondmodel',
            name='pymt_perd',
            field=models.IntegerField(),
        ),
    ]
