# Generated by Django 3.1.6 on 2022-02-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0025_auto_20220228_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondmodel',
            name='dfrrd_rpymt_perd_units',
            field=models.CharField(choices=[('', 'Deferred Repayment Period Units'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-annually', 'Semi-annually'), ('Annually', 'Annually')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bondmodel',
            name='duratn_units',
            field=models.CharField(choices=[('', 'Duration Units'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-annually', 'Semi-annually'), ('Annually', 'Annually')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bondmodel',
            name='pymt_perd_units',
            field=models.CharField(choices=[('', 'Payment Period Unit'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-annually', 'Semi-annually'), ('Annually', 'Annually')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bondmodel',
            name='usage',
            field=models.IntegerField(choices=[('', 'Usage'), (360, 360), (365, 365)]),
        ),
    ]
