# Generated by Django 3.1.6 on 2022-02-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0026_auto_20220228_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondmodel',
            name='bnd_type',
            field=models.CharField(choices=[('', 'Bond Type'), ('Redeemable in Shares', 'Redeemable in Shares'), ('Constant Redemption Bond', 'Constant Redemption Bond'), ('Deferred Constant Redemption Bond', 'Deferred Constant Redemption Bond'), ('In Fine Bond', 'In Fine Bond')], max_length=50),
        ),
    ]
