# Generated by Django 3.1.6 on 2022-03-09 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0012_auto_20220308_2014'),
        ('jdaanalyticsapp', '0029_auto_20220304_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitymodel',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jdafinancialsapp.companymodel'),
        ),
    ]
